SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID

-- SELECT 
--     T.ANIMAL_ID
-- FROM (
--     SELECT
--         ANIMAL_ID,
--         NVL(NAME, 'NoName') AS NAME
--     FROM ANIMAL_INS
-- ) T
-- WHERE T.NAME = 'NoName'
-- ORDER BY T.ANIMAL_ID;

-- SELECT 
--     ANIMAL_ID
-- FROM ANIMAL_INS
-- WHERE NAME IS NULL
-- ORDER BY ANIMAL_ID;