-- ORACLE
SELECT
    T.FOOD_TYPE,
    T.REST_ID,
    T.REST_NAME,
    T.FAVORITES
FROM (
    SELECT
        FOOD_TYPE,
        REST_ID,
        REST_NAME,
        FAVORITES,
        RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RANKING
    FROM REST_INFO
    ORDER BY FAVORITES DESC
) T
WHERE RANKING = 1
ORDER BY FOOD_TYPE DESC