SELECT
    *
FROM (
      SELECT
          T1.NAME AS NAME,
          T1.DATETIME AS DATETIME
      FROM ANIMAL_INS T1
      LEFT JOIN ANIMAL_OUTS T2
      ON T1.ANIMAL_ID = T2.ANIMAL_ID 
      WHERE T2.DATETIME IS NULL
      ORDER BY T1.DATETIME
)
WHERE ROWNUM <= 3