-- FOOD_PRODUCT
-- FOOD_ORDER
-- 생산일자가 2022년 5월인
-- 식품 ID, 식품 이름, 총매출을 조회
-- 총매출 기준으로 내림차순, 식품 ID 오름차순


-- ORACLE
-- SELECT
--     T1.PRODUCT_ID,
--     T1.PRODUCT_NAME,
--     T1.PRICE * T2.AMOUNT AS TOTAL_SALES
-- FROM FOOD_PRODUCT T1
-- JOIN FOOD_ORDER T2
--   ON T1.PRODUCT_ID = T2.PRODUCT_ID
-- WHERE T2.PRODUCE_DATE BETWEEN TO_DATE('20220501', 'YYYYMMDD') AND TO_DATE('20220601', 'YYYYMMDD')
-- ORDER BY TOTAL_SALES DESC, PRODUCT_ID

SELECT
    T1.PRODUCT_ID,
    T1.PRODUCT_NAME,
    T1.PRICE * T2.TOTAL AS TOTAL_SALES
FROM FOOD_PRODUCT T1
JOIN (
    SELECT 
        PRODUCT_ID,
        SUM(AMOUNT) AS TOTAL
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= TO_DATE('20220501', 'YYYYMMDD') 
      AND PRODUCE_DATE < TO_DATE('20220601', 'YYYYMMDD')
    GROUP BY PRODUCT_ID
) T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID

    
