-- ORACLE
SELECT
    T.*
FROM (
    SELECT
        TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
) T
WHERE T.HOUR BETWEEN 9 AND 19
ORDER BY T.HOUR
