--ORACLE
-- SELEC
--     *
-- FROM MEMBER_PROFILE

-- SELECT
--     T1.MEMBER_NAME,
--     T2.REVIEW_TEXT,
--     T2.REVIEW_DATE
-- FROM MEMBER_PROFILE T1
-- JOIN REST_REVIEW T2
--   ON T1.MEMBER_ID = T2.MEMBER_ID

-- SELECT
--     T1.MEMBER_NAME,
--     T2.REVIEW_TEXT,
--     T2.REVIEW_DATE
-- FROM MEMBER_PROFILE T1
-- JOIN (
--     SELECT
--         MEMBER_ID,
--         REVIEW_TEXT,
--         TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE,
--         COUNT(*) OVER(PARTITION BY MEMBER_ID) AS BEST_REVIEWER
--     FROM REST_REVIEW
--     WHERE COUNT(*) OVER(PARTITION BY MEMBER_ID) = 3
-- ) T2
-- ON T1.MEMBER_ID = T2.MEMBER_ID
-- ORDER BY T2.REVIEW_DATE, T2.REVIEW_TEXT

SELECT
    T1.MEMBER_NAME,
    TT.REVIEW_TEXT,
    TT.REVIEW_DATE
FROM MEMBER_PROFILE T1
JOIN (
    SELECT
        T2.MEMBER_ID,
        T2.REVIEW_TEXT,
        TO_CHAR(T2.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
    FROM REST_REVIEW T2
    JOIN (
        SELECT 
            MEMBER_ID, 
            RANK() OVER(ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) T3
    ON T2.MEMBER_ID = T3.MEMBER_ID
    WHERE T3.RNK = 1
) TT
ON T1.MEMBER_ID = TT.MEMBER_ID
ORDER BY TT.REVIEW_DATE, TT.REVIEW_TEXT