-- MCDP_CD: 진료과코드
-- MDDR_ID: 의사ID

-- ORACLE
SELECT
    MCDP_CD AS "진료과코드",
    COUNT(PT_NO) AS "5월예약건수"
FROM APPOINTMENT
WHERE APNT_YMD >= TO_DATE('20220501', 'YYYYMMDD')
AND APNT_YMD < TO_DATE('20220601', 'YYYYMMDD')
GROUP BY MCDP_CD
ORDER BY "5월예약건수", "진료과코드"