-- 코드를 입력하세요
SELECT
    T1.TITLE,
    T1.BOARD_ID,
    T2.REPLY_ID,
    T2.WRITER_ID,
    T2.CONTENTS,
    TO_CHAR(T2.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD T1
INNER JOIN USED_GOODS_REPLY T2 ON T1.BOARD_ID = T2.BOARD_ID
WHERE T1.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
ORDER BY T2.CREATED_DATE ASC, T1.TITLE ASC;