-- ORACLE
SELECT 
    T1.CATEGORY, 
    SUM(T2.SALES) AS TOTAL_SALES
FROM BOOK T1
JOIN BOOK_SALES T2 
  ON T1.BOOK_ID = T2.BOOK_ID
WHERE T2.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
  AND T2.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
GROUP BY T1.CATEGORY 
ORDER BY T1.CATEGORY